model_name: "deepseek_v3.2_exp"
model_path: "/data/models/DeepSeek-V3.2-Exp-W8A8C8" 
exe_mode: "acl_graph"          # ["ge_graph", "eager", "acl_graph"], mode of decode
world_size: 16               # world_size = 2 * chip_num in A3

model_config:
  next_n: 0
  pa_block_size: 16
  enable_weight_nz: True
  with_ckpt: True             # [False, True]
  enable_multi_streams: True  # [False, True]
  enable_profiler: False      # [False, True]
  perfect_eplb: False         # [False, True]
  enable_cache_compile: False  # [False, True]
  enable_online_split_weight: True # [False, True]
  prefill_mini_batch_size: 1
  enable_static_kernel: True  # [False, True] only support acl_graph

data_config:
  dataset: InfiniteBench
  input_max_len: 64
  max_new_tokens: 128
  batch_size: 256

parallel_config:
  cp_size: 16
  oproj_tp_size: 8    # only support when attn_tp_size == 1
  attn_tp_size: 1
  dense_tp_size: 4
  moe_tp_size: 1
  embed_tp_size: 16
  lmhead_tp_size: 16