model_name: "qwen3_moe"
model_path: "/data/models/origin/Qwen3-235B-A22B"
exe_mode: "ge_graph"        # ["ge_graph", "eager", "acl_graph"]
world_size: 128

model_config:
  enable_profiler: False  # [False, True]
  with_ckpt: True # [False, True]
  enable_cache_compile: False
  enable_online_split_weight: True # [False, True]
  perfect_eplb: False # [False, True]

data_config:
  dataset: "LongBench"  # ["default", "LongBench"]
  input_max_len: 4080
  max_new_tokens: 16
  batch_size: 128

parallel_config:
  attn_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 1
