model_name: "deepseek_r1"
model_path: "/data/models/origin/DeepSeek-R1-W8A8C8"
exe_mode: "ge_graph"                # ["ge_graph", "acl_graph", "eager"], mode of decode
world_size: 128

model_config:
  next_n: 3
  enable_pa: True                   # [False, True]
  pa_block_size: 128
  enable_mla_prolog: True           # [False, True]
  enable_weight_nz: True            # [False, True]
  with_ckpt: True                   # [False, True]
  enable_multi_streams: True        # [False, True]
  enable_profiler: False            # [False, True]
  perfect_eplb: False               # [False, True]
  enable_cache_compile: False       # [False, True]
  enable_online_split_weight: True   # [False, True]
  enable_prefill_multi_cycle: True # [False, True]
  moe_chunk_max_len: 512
  enable_superkernel: False         # [False, True]

data_config:
  dataset: "InfiniteBench"                # ["default", "LongBench", "InfiniteBench"]
  input_max_len: 65536
  max_new_tokens: 128
  batch_size: 256

parallel_config:
  attn_tp_size: 1
  dense_tp_size: 4
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 16
