model_name: "longcat_flash"
model_path: "/data/models/origin/LongCat-Flash-Chat/"
exe_mode: "ge_graph"                # ["ge_graph", "eager"], mode of decode
world_size: 32

model_config:
  enable_profiler: False  # [False, True]
  with_ckpt: True # [False, True]
  enable_online_split_weight: True
  pa_block_size: 128
  perfect_eplb: False     # [False, True]
  moe_chunk_max_len: 1024

data_config:
  dataset: "LongBench"                # ["default", "LongBench"]
  input_max_len: 4608
  max_new_tokens: 32
  batch_size: 64  # global batch_size, should be divisible by ep_size

parallel_config:
  attn_tp_size: 1 # attn_dp_size = world_size // attn_tp_size
  o_proj_tp_size: 1
  moe_tp_size: 1 # moe_ep_size = world_size // moe_tp_size
  dense_tp_size: 8
  embed_tp_size: 1
  lmhead_tp_size: 1