model_name: "gpt_oss_20b"
model_path: "your_model_path"
exe_mode: "eager"        # ["eager"]
world_size: 1

model_config:
  enable_profiler: False  # [False, True]
  enable_online_split_weight: True

data_config:
  dataset: "default"  # ["default", "LongBench"]
  input_max_len: 32
  max_new_tokens: 100
  batch_size: 1

parallel_config:  # Set the values of attn_tp_size, moe_tp_size, and lmhead_tp_size to be the same.
  attn_tp_size: 1  
  moe_tp_size: 1
  lmhead_tp_size: 1
